export const defaultSettings = {
  timezone: 'America/Mexico_City',
  locale: 'en-US',
  defaultBoardView: 'table',
  boardViews: {},
  notificationsEnabled: true,
  dashboardRefreshSeconds: 30,
  homePage: 'dashboard',
  density: 'comfortable',
  themeAccent: 'blue',
  sidebarCollapsed: false,
}

export const accentThemes = {
  blue: {
    accent: '#2563eb',
    accentSoft: '#dbeafe',
    accentContrast: '#eff6ff',
    appBg: '#eef4ff',
    appBgSoft: '#f8fbff',
    surface: '#ffffff',
    surfaceMuted: '#f4f8ff',
    border: '#c9ddff',
    textPrimary: '#0f172a',
    textSecondary: '#47607f',
  },
  amber: {
    accent: '#d97706',
    accentSoft: '#fef3c7',
    accentContrast: '#fffbeb',
    appBg: '#fff5e8',
    appBgSoft: '#fffaf2',
    surface: '#fffdf8',
    surfaceMuted: '#fff7e6',
    border: '#f3d3a2',
    textPrimary: '#3b2410',
    textSecondary: '#7c5a32',
  },
  emerald: {
    accent: '#059669',
    accentSoft: '#d1fae5',
    accentContrast: '#ecfdf5',
    appBg: '#ebfaf4',
    appBgSoft: '#f5fdf9',
    surface: '#fbfffd',
    surfaceMuted: '#eefcf5',
    border: '#b7ebd4',
    textPrimary: '#10261f',
    textSecondary: '#47675b',
  },
  rose: {
    accent: '#e11d48',
    accentSoft: '#ffe4e6',
    accentContrast: '#fff1f2',
    appBg: '#fff0f3',
    appBgSoft: '#fff8f9',
    surface: '#fffdfd',
    surfaceMuted: '#fff2f4',
    border: '#f7c8d1',
    textPrimary: '#32121b',
    textSecondary: '#7b4a57',
  },
  indigo: {
    accent: '#4f46e5',
    accentSoft: '#e0e7ff',
    accentContrast: '#eef2ff',
    appBg: '#eef2ff',
    appBgSoft: '#f8faff',
    surface: '#ffffff',
    surfaceMuted: '#eef2ff',
    border: '#c7d2fe',
    textPrimary: '#1e1b4b',
    textSecondary: '#5b5ea6',
  },
  teal: {
    accent: '#0f766e',
    accentSoft: '#ccfbf1',
    accentContrast: '#f0fdfa',
    appBg: '#e6fffb',
    appBgSoft: '#f4fffd',
    surface: '#fbfffe',
    surfaceMuted: '#e8fbf7',
    border: '#99f6e4',
    textPrimary: '#102a27',
    textSecondary: '#41756f',
  },
  coral: {
    accent: '#ea580c',
    accentSoft: '#ffedd5',
    accentContrast: '#fff7ed',
    appBg: '#fff1e8',
    appBgSoft: '#fff8f4',
    surface: '#fffefd',
    surfaceMuted: '#fff3ea',
    border: '#fdba74',
    textPrimary: '#3a1d10',
    textSecondary: '#8a583c',
  },
  violet: {
    accent: '#7c3aed',
    accentSoft: '#ede9fe',
    accentContrast: '#f5f3ff',
    appBg: '#f3efff',
    appBgSoft: '#faf8ff',
    surface: '#ffffff',
    surfaceMuted: '#f3efff',
    border: '#d8b4fe',
    textPrimary: '#2e1065',
    textSecondary: '#6b46a9',
  },
  lime: {
    accent: '#65a30d',
    accentSoft: '#ecfccb',
    accentContrast: '#f7fee7',
    appBg: '#f6ffe8',
    appBgSoft: '#fbfff3',
    surface: '#fefff9',
    surfaceMuted: '#f3fbdc',
    border: '#bef264',
    textPrimary: '#24340d',
    textSecondary: '#627244',
  },
  copper: {
    accent: '#b45309',
    accentSoft: '#fde6d3',
    accentContrast: '#fff7f1',
    appBg: '#fff3ea',
    appBgSoft: '#fff9f5',
    surface: '#fffefd',
    surfaceMuted: '#fff1e4',
    border: '#f5c39d',
    textPrimary: '#3a2214',
    textSecondary: '#82593e',
  },
  slate: {
    accent: '#334155',
    accentSoft: '#e2e8f0',
    accentContrast: '#f8fafc',
    appBg: '#eef2f6',
    appBgSoft: '#f8fafc',
    surface: '#ffffff',
    surfaceMuted: '#f1f5f9',
    border: '#d5dde7',
    textPrimary: '#111827',
    textSecondary: '#526071',
  },
  'blue-inverted': {
    accent: '#bfdbfe',
    accentSoft: '#1d4ed8',
    accentContrast: '#0f172a',
    appBg: '#0f172a',
    appBgSoft: '#162033',
    surface: '#111c2e',
    surfaceMuted: '#1b2a43',
    border: '#27476f',
    textPrimary: '#eff6ff',
    textSecondary: '#bfd6f6',
  },
  'emerald-inverted': {
    accent: '#a7f3d0',
    accentSoft: '#047857',
    accentContrast: '#081c15',
    appBg: '#081c15',
    appBgSoft: '#0d261d',
    surface: '#102b22',
    surfaceMuted: '#15352a',
    border: '#225244',
    textPrimary: '#ecfdf5',
    textSecondary: '#b7e9d1',
  },
  'rose-inverted': {
    accent: '#fecdd3',
    accentSoft: '#be123c',
    accentContrast: '#2a0d15',
    appBg: '#2a0d15',
    appBgSoft: '#34111b',
    surface: '#3f1621',
    surfaceMuted: '#4a1d2a',
    border: '#733049',
    textPrimary: '#fff1f2',
    textSecondary: '#f6c5cf',
  },
  'slate-inverted': {
    accent: '#cbd5e1',
    accentSoft: '#475569',
    accentContrast: '#0f172a',
    appBg: '#020617',
    appBgSoft: '#0b1220',
    surface: '#111827',
    surfaceMuted: '#182235',
    border: '#334155',
    textPrimary: '#f8fafc',
    textSecondary: '#cbd5e1',
  },
}
